<h2 class="archive search"><i class="zmdi zmdi-collection-text"></i><script>
    function getParameterByName(name) {
      var match = RegExp('[?&]' + name + '=([^&]*)').exec(window.location.search);
      return match && decodeURIComponent(match[1].replace(/\+/g, ' '));
    }
    document.write(getParameterByName('q'));
  </script>
</h2>
<div class="post mdl-shadow--2dp">
  <div class="post-content">
    <h2 style="margin-top: 0">Próximamente…</h2>
    {{ page.content }}
  </div>
</div>
