menu:
  - text: Gramática
    slug: Gramatica
  - text: Léxico
    slug:
  - text: Aprendizaje
    slug:
facebookID: '175199016196268'
analyticsID: UA-2285758-10
feed_url: https://feeds.feedburner.com/vivaverbo
subscriptionURL: http://eepurl.com/b18WXj
